"use strict";

const assert = require("assert");
const fs = require("fs");

const rules = JSON.parse(fs.readFileSync("database.rules.json", "utf8")).rules;
const customerPage = fs.readFileSync("index.html", "utf8");
const functionSource = fs.readFileSync("functions/index.js", "utf8");
const loyaltyPage = fs.readFileSync("loyalty.html", "utf8");
const adminPage = fs.readFileSync("admin.html", "utf8");
const customerRules = rules.loyalty_customers.$membership;
assert.equal(rules.loyalty_credentials[".read"], false);
assert.equal(rules.loyalty_credentials[".write"], false);
assert.equal(rules.loyalty_login_attempts[".read"], false);
assert.equal(rules.loyalty_login_attempts[".write"], false);
assert.equal(rules.subscription_pin_index[".read"], false);
assert.equal(rules.subscription_pin_index[".write"], false);
assert.equal(rules.loyalty_links.$uid[".write"], false);
assert.equal(customerRules[".read"].includes("loyalty_links"), false);
assert.equal(customerRules[".write"].includes("!data.exists() && newData.child('uid').val() === auth.uid"), false);
assert.match(customerPage, /httpsCallable\('loginWithMembership'\)/);
assert.match(customerPage, /httpsCallable\('provisionGoogleLoyalty'\)/);
assert.doesNotMatch(customerPage, /loyalty_links\/\$\{user\.uid\}.*\.(set|update|transaction|remove)\s*\(/);
assert.doesNotMatch(customerPage, /loyalty_credentials\/.*\.(set|update|transaction|remove)\s*\(/);
assert.doesNotMatch(customerPage, /loyalty_login_attempts\/.*\.(set|update|transaction|remove)\s*\(/);
assert.match(functionSource, /exports\.provisionGoogleLoyalty/);
assert.match(functionSource, /exports\.provisionGoogleSuperAdmin/);
assert.match(functionSource, /exports\.activatePendingLoyalty/);
assert.match(functionSource, /exports\.reserveClubPin/);
assert.match(functionSource, /exports\.changeLoyaltyMembership/);
assert.match(functionSource, /exports\.deleteLoyaltyCustomer/);
assert.match(functionSource, /email_verified/);
assert.match(functionSource, /loyalty_links\/\$\{uid\}/);
assert.match(loyaltyPage, /httpsCallable\('provisionGoogleSuperAdmin'\)/);
assert.match(adminPage, /httpsCallable\('provisionGoogleSuperAdmin'\)/);
assert.match(loyaltyPage, /httpsCallable\('changeLoyaltyMembership'\)/);
assert.match(loyaltyPage, /httpsCallable\('deleteLoyaltyCustomer'\)/);
assert.match(adminPage, /httpsCallable\('activatePendingLoyalty'\)/);
assert.match(adminPage, /httpsCallable\('reserveClubPin'\)/);
assert.doesNotMatch(loyaltyPage, /loyalty_links[^\r\n]*(set|update|transaction|remove)\s*\(/);
assert.doesNotMatch(adminPage, /loyalty_links[^\r\n]*(set|update|transaction|remove)\s*\(/);
assert.doesNotMatch(adminPage, /subscription_pin_index[^\r\n]*(set|update|transaction|remove)\s*\(/);
console.log("security migration rules static tests: PASS");
