
/* Gift ordering is intentionally isolated from cart/checkout state. */
let giftSettings = { enabled:true, accountName:'', transferNumber:'', whatsapp:'', defaultExpiryDays:30, minValue:5000, maxValue:100000, allowAnonymous:true };
let giftSelection = { type:'', productIds:[], value:0 };
const giftMoney = n => `${Number(n||0).toLocaleString('en-US')} د.ع`;
const giftEligibleProducts = () => (Array.isArray(products) ? products : []).filter(p => p && p.enabled !== false && p.available !== false && !p.hidden && !p.comingSoon);
function openGiftExperience(){ const modal=document.getElementById('giftBackdrop'); if(!modal)return; modal.hidden=false; document.body.style.overflow='hidden'; renderGiftChoices(); refreshGiftPayment(); }
function closeGiftExperience(){ const modal=document.getElementById('giftBackdrop'); if(modal) modal.hidden=true; document.body.style.overflow=''; }
function giftValueForSelection(){ if(giftSelection.type==='value') return Number(giftSelection.value||0); return giftSelection.productIds.reduce((total,id)=>{const p=giftEligibleProducts().find(x=>String(x.id)===String(id));return total+Number(p?.price||0)},0); }
function refreshGiftPreview(){ const recipient=document.getElementById('giftRecipientName')?.value.trim(); const sender=document.getElementById('giftSenderName')?.value.trim(); const anonymous=document.getElementById('giftAnonymous')?.checked; const chosen=giftSelection.productIds.map(id=>giftEligibleProducts().find(p=>String(p.id)===String(id))?.name).filter(Boolean); document.getElementById('giftPreviewRecipient').textContent=recipient?`إلى: ${recipient}`:'إلى شخص مميز'; document.getElementById('giftPreviewSender').textContent=anonymous?'من شخص يحبك ❤️':(sender?`من: ${sender}`:'من شخص يحبك ❤️'); document.getElementById('giftPreviewValue').textContent=giftSelection.type==='value'?(giftSelection.value?giftMoney(giftSelection.value):'اختر قيمة الهدية'):(chosen.join(' + ')||'اختر هديتك'); refreshGiftPayment(); }
function refreshGiftPayment(){ const total=giftValueForSelection(); const submit=document.getElementById('giftSubmit'); document.getElementById('giftTotal').textContent=total?giftMoney(total):'—'; document.getElementById('giftAccountName').textContent=giftSettings.accountName||'غير مُعدّ بعد'; document.getElementById('giftTransferNumber').textContent=giftSettings.transferNumber||'غير مُعدّ بعد'; document.getElementById('giftPaymentCopy').textContent=giftSettings.paymentMessage||'لحجز الهدية وتثبيتها، يرجى تحويل المبلغ ثم إرسال صورة التحويل عبر WhatsApp.'; if(submit) submit.disabled=!giftSettings.enabled || !giftSettings.transferNumber || !total; }
function renderGiftChoices(){ const types=document.getElementById('giftTypes'); if(!types)return; types.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.giftType===giftSelection.type)); const productBox=document.getElementById('giftProductChoices'), valueBox=document.getElementById('giftValueChoices'); const isProduct=['drink','dessert','combo'].includes(giftSelection.type); productBox.hidden=!isProduct; valueBox.hidden=giftSelection.type!=='value'; if(isProduct){ const typeLabel=giftSelection.type==='drink'?'مشروب':giftSelection.type==='dessert'?'حلى':'مشروب أو حلى'; const list=giftEligibleProducts().filter(p=>giftSelection.type==='combo'||(giftSelection.type==='drink'?/coffee|قهوة|مشروب|drink/i.test(`${p.category||''} ${p.name||''}`):/حلى|dessert|cake|كيك/i.test(`${p.category||''} ${p.name||''}`))); productBox.innerHTML=list.length?`<p style="grid-column:1/-1;margin:0 0 4px">اختر ${giftSelection.type==='combo'?'منتجاً أو أكثر':typeLabel} من المنيو</p>`+list.map(p=>`<button type="button" data-gift-product="${esc(p.id)}" class="${giftSelection.productIds.includes(String(p.id))?'selected':''}">${esc(p.name)}<br><small>${giftMoney(p.price)}</small></button>`).join(''):'<p>لا توجد منتجات متاحة حالياً.</p>'; } if(giftSelection.type==='value'){ const values=[5000,10000,15000,20000,25000]; valueBox.innerHTML=values.map(v=>`<button type="button" data-gift-value="${v}" class="${Number(giftSelection.value)===v?'selected':''}">${giftMoney(v)}</button>`).join('')+`<button type="button" id="giftCustomValueBtn">مبلغ مخصص</button><input id="giftCustomValue" type="number" min="${giftSettings.minValue||1}" max="${giftSettings.maxValue||9999999}" inputmode="numeric" placeholder="مبلغ مخصص د.ع" value="${values.includes(Number(giftSelection.value))?'':(giftSelection.value||'')}">`; } refreshGiftPreview(); }
document.addEventListener('click',event=>{ const type=event.target.closest('[data-gift-type]'); if(type){giftSelection={type:type.dataset.giftType,productIds:[],value:0};renderGiftChoices();return;} const product=event.target.closest('[data-gift-product]');if(product){const id=String(product.dataset.giftProduct);if(giftSelection.type==='combo')giftSelection.productIds=giftSelection.productIds.includes(id)?giftSelection.productIds.filter(x=>x!==id):[...giftSelection.productIds,id];else giftSelection.productIds=[id];renderGiftChoices();return;}const value=event.target.closest('[data-gift-value]');if(value){giftSelection.value=Number(value.dataset.giftValue);renderGiftChoices();}});
document.addEventListener('input',event=>{ if(event.target.matches('#giftSenderName,#giftRecipientName'))refreshGiftPreview(); if(event.target.id==='giftMessage')document.getElementById('giftMessageCount').textContent=`${event.target.value.length} / 150`; if(event.target.id==='giftCustomValue'){giftSelection.value=Number(event.target.value||0);refreshGiftPreview();}});
document.addEventListener('change',event=>{if(event.target.id==='giftAnonymous')refreshGiftPreview();});
document.getElementById('giftCopyTransfer')?.addEventListener('click',async()=>{if(!giftSettings.transferNumber)return;try{await navigator.clipboard.writeText(giftSettings.transferNumber);showToast('تم نسخ رقم التحويل.','success');}catch(e){showToast('تعذر نسخ الرقم.','error');}});
});
function initGiftSettings(){if(!db)return;db.ref('gift_settings').on('value',snap=>{giftSettings={...giftSettings,...(snap.val()||{})};renderGiftChoices();refreshGiftPayment();}););}
const initGiftWhenReady=()=>{initGiftSettings();}; if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initGiftWhenReady,{once:true});else initGiftWhenReady();
