import assert from 'node:assert/strict';
import { createPrivateKey, createPublicKey, createSign, generateKeyPairSync } from 'node:crypto';
import { createCredential } from '../src/loyalty-security.js';
import { handleLoyaltyRoutes } from '../src/loyalty-routes.js';

const { privateKey, publicKey } = generateKeyPairSync('rsa', { modulusLength: 2048 });
const key = createPrivateKey(privateKey.export({ type: 'pkcs8', format: 'pem' }));
const env = { ALLOWED_ORIGINS: 'https://101coffees.com', FIREBASE_DATABASE_URL: 'https://fixture.firebaseio.test', FIREBASE_SERVICE_ACCOUNT_EMAIL: 'fixture@example.test', FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY: key.export({ type: 'pkcs8', format: 'pem' }), LOYALTY_PIN_PEPPER: 'fixture-pepper' };
const root = { loyalty_customers: { '101-78': { uid: 'member-78', pin: '5678', currentHearts: 2 }, '101-79': { uid: 'member-79', pin: '1357', currentHearts: 1 } }, loyalty_links: { 'member-78': '101-78', 'member-79': '101-79' }, loyalty_credentials: { '101-78': await createCredential('5678', env.LOYALTY_PIN_PEPPER) } };
const publicJwk = publicKey.export({ format: 'jwk' });
function token(uid, membership) { const head = Buffer.from(JSON.stringify({ alg: 'RS256', typ: 'JWT', kid: 'fixture-key' })).toString('base64url'); const body = Buffer.from(JSON.stringify({ sub: uid, aud: 'coffee-30fa7', iss: 'https://securetoken.google.com/coffee-30fa7', iat: Math.floor(Date.now() / 1000) - 5, exp: Math.floor(Date.now() / 1000) + 3600, email: `${uid}@example.test`, email_verified: true, loyaltyMembership: membership })).toString('base64url'); const signer = createSign('RSA-SHA256'); signer.update(`${head}.${body}`); return `${head}.${body}.${signer.sign(key).toString('base64url')}`; }
function setPath(path, value) { const parts = path.split('/').filter(Boolean); let target = root; for (const part of parts.slice(0, -1)) target = target[part] ||= {}; if (value === null) delete target[parts.at(-1)]; else target[parts.at(-1)] = value; }
globalThis.fetch = async (url, options = {}) => { const address = String(url); if (address.includes('googleapis.com/service_accounts')) return Response.json({ keys: [{ ...publicJwk, kid: 'fixture-key', alg: 'RS256', use: 'sig' }] }); if (address === 'https://oauth2.googleapis.com/token') return Response.json({ access_token: 'fixture-access', expires_in: 3600 }); if (!address.startsWith(env.FIREBASE_DATABASE_URL)) throw new Error(`unexpected fixture request: ${address}`); const path = decodeURIComponent(new URL(address).pathname).replace(/^\//, '').replace(/\.json$/, ''); if (options.method === 'PUT' || options.method === 'PATCH') { const value = JSON.parse(options.body); if (options.method === 'PATCH' && !path) for (const [key, item] of Object.entries(value)) setPath(key, item); else setPath(path, value); return Response.json({}); } let value = root; for (const part of path ? path.split('/') : []) value = value?.[part]; return new Response(JSON.stringify(value ?? null), { headers: { 'Content-Type': 'application/json' } }); };
async function post(auth) { const request = new Request('https://worker.test/api/loyalty/reveal-pin', { method: 'POST', headers: { Origin: env.ALLOWED_ORIGINS, Authorization: `Bearer ${auth}`, 'Content-Type': 'application/json' }, body: '{}' }); const response = await handleLoyaltyRoutes(request, env, new URL(request.url)); return { status: response.status, body: await response.json() }; }
let result = await post(token('member-78', '101-79')); assert.equal(result.status, 200); assert.equal(result.body.pin, '5678'); assert.equal(result.body.pinHash, undefined); assert.equal(result.body.salt, undefined);
result = await post(token('member-79', '101-78')); assert.equal(result.status, 200); assert.equal(result.body.pin, '1357'); assert.notEqual(result.body.pin, root.loyalty_customers['101-78'].pin);
result = await post(token('unlinked', '101-78')); assert.equal(result.status, 404); assert.equal(result.body.pin, undefined);
console.log('loyalty reveal ownership fixtures: PASS');
