import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const [index, loyalty, admin, rules] = await Promise.all([
  readFile(join(root, 'index.html'), 'utf8'),
  readFile(join(root, 'loyalty.html'), 'utf8'),
  readFile(join(root, 'admin.html'), 'utf8'),
  readFile(join(root, 'database.rules.json'), 'utf8')
]);
assert.match(index, /\/api\/loyalty\/login/);
assert.match(index, /\/api\/loyalty\/profile/);
assert.match(index, /\/api\/loyalty\/provision-google/);
assert.match(index, /\/api\/subscription\/me/);
assert.doesNotMatch(index, /subscription_customers['"]\.orderByChild\(['"]uid/);
assert.match(index, /mobileAuthTrace\('AUTH_START'/);
assert.match(index, /mobileAuthTrace\('REDIRECT_RETURN'/);
assert.match(index, /mobileAuthTrace\('REDIRECT_RESULT'/);
assert.match(index, /mobileAuthTrace\('AUTH_STATE'/);
assert.match(index, /mobileAuthTrace\('ID_TOKEN'/);
assert.match(index, /mobileAuthTrace\('PROVISION_HTTP'/);
assert.match(index, /mobileAuthTrace\('PROVISION_RESULT'/);
assert.match(index, /mobileAuthTrace\('MEMBERSHIP_LINK'/);
assert.match(index, /mobileAuthTrace\('UI_RENDER'/);
assert.match(index, /MOBILE_AUTH_ERROR/);
assert.match(index, /PROFILE_LINK_CONFLICT/);
assert.match(index, /functions\/PROFILE_LINK_CONFLICT/);
assert.match(loyalty, /\/api\/admin\/provision-super-admin/);
assert.match(admin, /\/api\/admin\/provision-super-admin/);
assert.match(admin, /function canRevealMemberPin\(\)/);
assert.match(admin, /setTimeout\(\(\) => \{ el\.textContent = '••••'/);
assert.doesNotMatch(admin, /فحص وإصلاح كشف PIN|auditAndRepairPinReveals|reauthenticateWithPopup|pin-reveal-audit/);
const safeDiagnostics = admin.match(/error\.safeDiagnostics\s*=\s*\{[\s\S]*?\n\s*\};/)?.[0] || '';
assert.match(safeDiagnostics, /stage/);
assert.match(safeDiagnostics, /code/);
assert.match(safeDiagnostics, /firebaseOp/);
assert.match(safeDiagnostics, /firebaseStatus/);
assert.doesNotMatch(safeDiagnostics, /token|pin|hash|salt|pepper|uid|phone|body|stack/i);
assert.equal(JSON.parse(rules).rules.loyalty_links.$uid['.read'], false);
assert.equal(JSON.parse(rules).rules.loyalty_links.$uid['.write'], false);
assert.doesNotMatch(index, /httpsCallable\(['"](?:loginWithMembership|getMyLoyaltyProfile|provisionGoogleLoyalty|provisionGoogleSuperAdmin)['"]\)/);
assert.match(index, /Your rewards balance is temporarily unavailable/);
assert.match(index, /إعادة المحاولة/);
assert.match(index, /تسجيل الدخول للمكافآت/);
const worker = await readFile(join(root, 'cloudflare-worker', 'src', 'loyalty-routes.js'), 'utf8');
assert.match(worker, /PROFILE_LINK_CONFLICT/);
assert.match(worker, /AUTH_START/);
assert.match(worker, /PROFILE_LOOKUP/);
assert.match(worker, /UID_LINK_CHECK/);
assert.match(worker, /COUNTER_READ/);
assert.match(worker, /COUNTER_RESERVE/);
assert.match(worker, /PIN_GENERATE/);
assert.match(worker, /CREDENTIAL_CREATE/);
assert.match(worker, /PIN_ENCRYPT/);
assert.match(worker, /FIREBASE_WRITE/);
assert.match(worker, /PROFILE_READBACK/);
assert.match(worker, /COMPLETE/);
assert.match(worker, /loyalty_provision_reservations/);
assert.match(worker, /X-Request-ID/);
assert.match(worker, /X-Worker-Build/);
assert.match(worker, /verifyPinForReveal/);
assert.doesNotMatch(worker, /return response\(request, env, \{ ok: true, available: true, pin \}\)/);
assert.doesNotMatch(worker, /PIN_BACKFILL_MISSING/);
assert.match(worker, /firebaseAdminConditionalPut/);
assert.match(worker, /async function subscriptionMe/);
assert.match(worker, /\/api\/subscription\/me/);
assert.match(worker, /async function revealPinForAdmin/);
assert.match(worker, /canRevealMemberPin/);
assert.doesNotMatch(worker, /pin-reveal-audit|AUTH_RECENT_REQUIRED/);
assert.match(worker, /safeSubscriptionMe/);
assert.match(worker, /pinIndexKey/);
assert.match(worker, /loyalty-member:\$\{membership\}/);
assert.doesNotMatch(worker, /Math\.random/);
assert.doesNotMatch(loyalty, /Math\.random/);
assert.doesNotMatch(admin, /Math\.random/);
assert.match(loyalty, /\/api\/admin\/loyalty\/create/);
assert.match(loyalty, /pendingNewCustomerRequestId/);
assert.match(loyalty, /body: \{ requestId, name, phone, hearts, memberType \}/);
assert.match(loyalty, /const hearts = heartsRaw === '' \? 0 : Number\(heartsRaw\)/);
assert.match(loyalty, /INVALID_FIELD/);
assert.match(loyalty, /const newCardId = result\.membershipNumber/);
assert.match(loyalty, /تعذر الاتصال بخدمة العضويات/);
assert.match(worker, /const replay = replayOrPlan\(root, 'customer-create', id\)/);
assert.match(worker, /replay\.result\.actorUid !== current\.uid/);
assert.match(worker, /PIN_REVEAL_WRITE_UNVERIFIED/);
assert.match(worker, /\[operationPath\('customer-create', id\)\]/);
assert.match(worker, /invalidField\('hearts'\)/);
const giftRedeem = worker.match(/async function redeemGift[\s\S]*?async function listGiftOrders/)[0];
assert.match(giftRedeem, /firebaseAdminReadWithEtag\(env, `gift_orders\/\$\{id\}`\)/);
assert.match(giftRedeem, /firebaseAdminConditionalPut\(env, `gift_orders\/\$\{id\}`/);
assert.doesNotMatch(giftRedeem, /atomicPlan/);
assert.match(giftRedeem, /GIFT_REDEEM_WRITE_START/);
assert.match(giftRedeem, /CONCURRENT_MODIFICATION/);
assert.match(loyalty, /giftId:gift\.id,giftCode:gift\.giftCode,orderCode:gift\.orderCode,recipientPhone:gift\.recipientPhone/);
assert.match(loyalty, /CONCURRENT_MODIFICATION:'تم تحديث الهدية، أعد البحث\.'/);
assert.match(index, /summaryPinToggle[^>]*>🐵/);
assert.match(index, /\/api\/loyalty\/reveal-pin/);
assert.doesNotMatch(index, /Enter your PIN to verify ownership/);
assert.match(index, /setTimeout\(hidePinVisibility, 15000\)/);
assert.doesNotMatch(index, /localStorage[^\n]*userPinRaw/);
console.log('worker loyalty static checks: PASS');
